### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by ArtemSultanov** [OS-IS/ai201-sultanov#1]

**Comment by ArtemSultanov** [comment]
<img width="661" alt="Снимок экрана 2024-09-21 в 16 00 18" src="https://github.com/user-attachments/assets/4221003c-d540-4a90-b383-87811007c8c7">

**Comment by ArtemSultanov** [comment]
<img width="664" alt="Снимок экрана 2024-09-21 в 16 07 47" src="https://github.com/user-attachments/assets/318d598d-ed08-4a6d-9f59-7f72872a90af">

**Comment by ArtemSultanov** [comment]
<img width="596" alt="Снимок экрана 2024-09-21 в 17 11 08" src="https://github.com/user-attachments/assets/2ad45d83-5005-497d-b7b2-e30b51fd67c4">

**Comment by ArtemSultanov** [comment]
![1](https://github.com/user-attachments/assets/28e21b72-e5fd-48c4-99f5-332151507640)

**Comment by ArtemSultanov** [comment]
![2](https://github.com/user-attachments/assets/27c280b9-bc89-4479-9b5d-9e656be69fc0)

**Comment by ArtemSultanov** [comment]
![3](https://github.com/user-attachments/assets/85c2ac2c-1984-490b-8978-731f992e43a0)

**Comment by ArtemSultanov** [comment]
![4](https://github.com/user-attachments/assets/3af17175-6674-4277-bee8-55db13508758)

**Comment by ArtemSultanov** [comment]
![5](https://github.com/user-attachments/assets/cad01f29-67bd-49da-a44d-ea87ef04c7c3)

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 5 балів.
Дякую
